[package]
name = "rsc2_pb"
version = "0.1.0"
authors = ["hyyking <leoduret@outlook.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
bytes = "0.4.7"
prost = {git = "https://github.com/hyyking/prost.git"}
websocket = {version="0.23.*", features=["async"]}
rsc2_derive = {path="../rsc2-derive"}

[build-dependencies]
prost-build = {git = "https://github.com/hyyking/prost.git"}

