[package]
name = "rsc2_pb"
version = "0.1.0"
authors = ["hyyking <leoduret@outlook.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
bytes = "^0.4.12"
prost = {git = "https://github.com/hyyking/prost.git"}
websocket = "0.23.*"

[build-dependencies]
prost-build = {git = "https://github.com/hyyking/prost.git"}

