[package]
name = "rsc2_pb"
version = "0.1.0"
authors = ["hyyking <leoduret@outlook.com>"]
edition = "2018"
build = "build.rs"

[features]
default = ["rsc2_derive", "prost", "bytes"]
codec = ["tokio-codec", "tokio-net", "websocket-codec"]

[dependencies]
# default
prost = {git = "https://github.com/hyyking/prost.git", optional=true}
bytes = {version = "0.4.7", optional=true}
rsc2_derive = {path="../rsc2-derive", optional=true}

# codec
websocket-codec = {version="0.2.1-alpha.6", optional=true}
tokio-codec = {version="0.2.0-alpha.6", optional=true}
tokio-net = {version="0.2.0-alpha.6", optional=true}

[build-dependencies]
prost-build = {git = "https://github.com/hyyking/prost.git"}
git2 = "0.10.1" # check for a better solution (maybe cargo-like)
