[package]
name = "rsc2_derive"
version = "0.1.0"
authors = ["hyyking <leoduret@outlook.com>"]
edition = "2018"

[lib]
proc_macro=true

[[test]]
name = "derive"
path = "../tests/derive.rs"


[dependencies]
syn = {version="1.0.*", features=["extra-traits"]}
quote = "1.0.*"
