[package]
name = "rsc2"
version = "0.1.0"
authors = ["hyyking <leoduret@outlook.com>"]
edition = "2018"

[features]
default = ["logging"]
logging = ["log", "pretty_env_logger"]

[dependencies]
# Core
rsc2_pb = {path="../rsc2-pb"}
websocket = {version= "0.23.0", features=["async"]}
tokio = "0.1"
bytes = "0.4"
prost = {git = "https://github.com/hyyking/prost.git"}

# Logging
log = {version="0.4.8", features=["max_level_trace", "release_max_level_info"], optional=true}
pretty_env_logger = {version="0.3.1", optional=true}
