[package]
name = "rsc2"
version = "0.1.0"
authors = ["hyyking <leoduret@outlook.com>"]
edition = "2018"

[dependencies]
rsc2_pb = {path="../rsc2-pb", features=["default", "codec"]}
tokio = {version = "0.2.0-alpha.6", features=["rt-full"]}
websocket-lite = "0.3.1-alpha.6"
futures-preview = "0.3.0-alpha.19"
pin-utils = "0.1.0-alpha.4"
log = "0.4.8"

[[test]]
name = "runtime"
path = "../tests/runtime.rs"
