[package]
name = "rsc2"
version = "0.1.0"
authors = ["hyyking <leoduret@outlook.com>"]
edition = "2018"

[dependencies]
rsc2_pb = {path="../rsc2-pb", features=["codec"]}
tokio = "0.2.0-alpha.6"
websocket-lite = "0.3.1-alpha.6"
futures-preview = "0.3.0-alpha.19"
